# 2. Images as arrays exercises

1. Import Numpy

2. Create a 6 rows, 4 columns array of 1s called ```my_array```. Using the ```shape``` parameter make sure the size is correct.

3. Modify the element at row = 3, column = 1 to be 50

4. Modify the array by multiplying all its values by 3

5. Using Google, find the Numpy function to take the square root and create a new array called ```my_array_root``` by applying it to your current ```my_array```.

6. Create a new array called ```my_array_sum``` by multiplying ```my_array``` and ```my_array_root```

7. Find the maximum value of your array by using either a methods or a function

8. Create a boolean array where only places in ```my_array_sum``` which are larger than 100 are ```True```.

9. Recover all the values in ```my_array_sum``` which are true in the boolean array using logical indexing. What is the shape of the array containing these values?

In [3]:
# 1. Import Numpy
import numpy as np

# 2. Create a 6 rows, 4 columns array of 1s called my_array
my_array = np.ones((6, 4))

# 3. Modify the element at row = 3, column = 1 to be 50
my_array[2, 0] = 50  # Note that row and column indices are zero-based

# 4. Modify the array by multiplying all its values by 3
my_array *= 3

# 5. Use the Numpy function to take the square root and create a new array called my_array_root
my_array_root = np.sqrt(my_array)

# 6. Create a new array called my_array_sum by multiplying my_array and my_array_root
my_array_sum = my_array * my_array_root

# 7. Find the maximum value of your array using the np.max function
max_value = np.max(my_array_sum)

# 8. Create a boolean array where only places in my_array_sum which are larger than 100 are True
boolean_array = my_array_sum > 100

# 9. Recover all the values in my_array_sum which are True in the boolean array using logical indexing
values_greater_than_100 = my_array_sum[boolean_array]

# The shape of the array containing these values can be determined using the shape attribute
shape_of_values = values_greater_than_100.shape

print("Max Value in my_array_sum:", max_value)
print("Values in my_array_sum greater than 100:", values_greater_than_100)
print("Shape of the values array:", shape_of_values)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Max Value in my_array_sum: 1837.1173070873836
Values in my_array_sum greater than 100: [1837.11730709]
Shape of the values array: (1,)
