In [24]:
# Import Libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

# Baca Dataset
dataset = pd.read_csv('milk.csv')
display(dataset.tail())

# Masukkan training data (Semua dari dataset)
train_data = np.array(dataset)[:,0:-1]
train_label = np.array(dataset)[:,-1]

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
1054  6.7          45      1     1     0          0     247  medium
1055  6.7          38      1     0     1          0     255    high
1056  3.0          40      1     1     1          1     255     low
1057  6.8          43      1     0     1          0     250    high
1058  8.6          55      0     1     1          1     255     low

In [14]:
# Normalisasi Min Max
sc = MinMaxScaler(feature_range = (0,1))

data = sc.fit_transform(train_data)
print(data)

[[0.55384615 0.01785714 1.         ... 1.         0.         0.93333333]
 [0.55384615 0.03571429 0.         ... 0.         1.         0.86666667]
 [0.84615385 0.64285714 1.         ... 1.         1.         0.4       ]
 ...
 [0.         0.10714286 1.         ... 1.         1.         1.        ]
 [0.58461538 0.16071429 1.         ... 1.         0.         0.66666667]
 [0.86153846 0.375      0.         ... 1.         1.         1.        ]]


In [18]:
# Deklarasi fungsi kNN, k = 3
kNN = KNeighborsClassifier(n_neighbors=3, weights='distance')
# Implementasi kNN ke training data
kNN.fit(train_data, train_label)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [21]:
# Input data
pH = input("pH: ")
Temp = input("Temp: ")
Taste = input("Taste: ")
Odor = input("Odor: ")
Fat = input("Fat: ")
Turbidity = input("Turbidity: ")
Colour = input("Colour: ")

test_data = np.array([float(pH), float(Temp), int(Taste), int(Odor), int(Fat), int(Turbidity), int(Colour)])
print(test_data)

pH: 6.7
Temp: 45
Taste: 1
Odor: 1
Fat: 0
Turbidity: 0
Colour: 247
[  6.7  45.    1.    1.    0.    0.  247. ]


In [22]:
# Reshape data agar sesuai
test_data = np.reshape(test_data,(1,-1))
print(test_data)

[[  6.7  45.    1.    1.    0.    0.  247. ]]


In [23]:
# Predict label
hasil = kNN.predict(test_data)

# Output
print("Hasil dari k-NN: ", hasil)

Hasil dari k-NN:  ['medium']
