In [25]:
# Import Libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

# Baca Dataset Training
training_dataset = pd.read_csv('milk_training.csv')
display(training_dataset.tail())

# Masukkan training data (Semua dari training_dataset)
train_data = np.array(training_dataset)[:,0:-1]
train_label = np.array(training_dataset)[:,-1]

pH  Temprature  Taste  Odor  Fat  Turbidity  Colour   Grade
737  6.7          45      1     1    1          0     245  medium
738  6.5          38      1     0    1          0     255  medium
739  6.7          41      1     0    0          0     247  medium
740  6.8          41      0     0    0          0     255  medium
741  6.8          38      0     0    0          0     255  medium

In [26]:
# Normalisasi Min Max
sc = MinMaxScaler(feature_range = (0,1))

train_data = sc.fit_transform(train_data)
print(train_data)

[[0.55384615 0.01785714 1.         ... 1.         0.         0.93333333]
 [0.55384615 0.03571429 0.         ... 0.         1.         0.86666667]
 [0.55384615 0.05357143 1.         ... 1.         1.         1.        ]
 ...
 [0.56923077 0.125      1.         ... 0.         0.         0.46666667]
 [0.58461538 0.125      0.         ... 0.         0.         1.        ]
 [0.58461538 0.07142857 0.         ... 0.         0.         1.        ]]


In [27]:
# Baca Dataset Testing
testing_dataset = pd.read_csv('milk_testing.csv')
display(testing_dataset)

# Masukkan testing data (Semua dari testing_dataset)
test_data = np.array(testing_dataset)[:,0:-1]
test_label = np.array(testing_dataset)[:,-1]

pH  Temprature  Taste  Odor  Fat  Turbidity  Colour   Grade
0    6.8          45      1     1    1          0     245    high
1    6.6          37      1     1    1          1     255    high
2    6.7          38      1     0    1          0     255    high
3    6.8          45      0     1    1          1     255    high
4    6.6          37      1     1    1          1     255    high
..   ...         ...    ...   ...  ...        ...     ...     ...
312  6.5          36      0     0    0          0     247  medium
313  6.6          38      0     0    0          0     255  medium
314  6.5          37      0     0    0          0     255  medium
315  6.5          40      1     0    0          0     250  medium
316  6.7          45      1     1    0          0     247  medium

[317 rows x 8 columns]

In [28]:
# Normalisasi Min Max Testing Data
sc = MinMaxScaler(feature_range = (0,1))

test_data = sc.fit_transform(test_data)
print(test_data)

[[0.58461538 0.19642857 1.         ... 1.         0.         0.33333333]
 [0.55384615 0.05357143 1.         ... 1.         1.         1.        ]
 [0.56923077 0.07142857 1.         ... 1.         0.         1.        ]
 ...
 [0.53846154 0.05357143 0.         ... 0.         0.         1.        ]
 [0.53846154 0.10714286 1.         ... 0.         0.         0.66666667]
 [0.56923077 0.19642857 1.         ... 0.         0.         0.46666667]]


In [29]:
# Deklarasi fungsi kNN, k = 3
kNN = KNeighborsClassifier(n_neighbors=3, weights='distance')
# Implementasi kNN ke training data
kNN.fit(train_data, train_label)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [32]:
# Predict label
hasil = kNN.predict(test_data)

# Nilai akurasi
Score = accuracy_score(test_label, hasil)
print('Nilai akurasi: ',Score)

# Output
print("\nHasil dari k-NN: ", hasil)

Nilai akurasi:  0.9936908517350158

Hasil dari k-NN:  ['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'l